name: 'Install dependencies'
description: 'Prepare repository and all dependencies'

runs:
  using: 'composite'
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@v4

    - name: Set up Node
      uses: actions/setup-node@v6
      with:
        cache: 'pnpm'
        node-version: '24.12.0'

    - name: Install dependencies
      shell: bash
      run: pnpm install
