/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as BridgeRouteImport } from './routes/_bridge'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAddressRouteImport } from './routes/_layout/$address'
import { Route as BridgeBridgeRouteRouteImport } from './routes/_bridge/bridge/route'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgeRoute = BridgeRouteImport.update({
  id: '/_bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAddressRoute = LayoutAddressRouteImport.update({
  id: '/$address',
  path: '/$address',
  getParentRoute: () => LayoutRoute,
} as any)
const BridgeBridgeRouteRoute = BridgeBridgeRouteRouteImport.update({
  id: '/bridge',
  path: '/bridge',
  getParentRoute: () => BridgeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/bridge': typeof BridgeBridgeRouteRoute
  '/$address': typeof LayoutAddressRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/bridge': typeof BridgeBridgeRouteRoute
  '/$address': typeof LayoutAddressRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_bridge': typeof BridgeRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/_bridge/bridge': typeof BridgeBridgeRouteRoute
  '/_layout/$address': typeof LayoutAddressRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/bridge' | '/$address' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/bridge' | '/$address' | '/'
  id:
    | '__root__'
    | '/_bridge'
    | '/_layout'
    | '/_bridge/bridge'
    | '/_layout/$address'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  BridgeRoute: typeof BridgeRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_bridge': {
      id: '/_bridge'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof BridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$address': {
      id: '/_layout/$address'
      path: '/$address'
      fullPath: '/$address'
      preLoaderRoute: typeof LayoutAddressRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_bridge/bridge': {
      id: '/_bridge/bridge'
      path: '/bridge'
      fullPath: '/bridge'
      preLoaderRoute: typeof BridgeBridgeRouteRouteImport
      parentRoute: typeof BridgeRoute
    }
  }
}

interface BridgeRouteChildren {
  BridgeBridgeRouteRoute: typeof BridgeBridgeRouteRoute
}

const BridgeRouteChildren: BridgeRouteChildren = {
  BridgeBridgeRouteRoute: BridgeBridgeRouteRoute,
}

const BridgeRouteWithChildren =
  BridgeRoute._addFileChildren(BridgeRouteChildren)

interface LayoutRouteChildren {
  LayoutAddressRoute: typeof LayoutAddressRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAddressRoute: LayoutAddressRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  BridgeRoute: BridgeRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
